services:
  - type: web
    name: elt-riskmanagementdash
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors *; default-src * 'unsafe-inline' 'unsafe-eval' data: blob:"

      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
